---
title: Presentation Title
format:
  #minimal-revealjs: default
  minimal-beamer: default
author: Filippo Gambarota
email: filippo.gambarota@unipd.it
web: filippogambarota.github.io
date: last-modified
institute: University of Padova
date-format: "[\\@EVENT] YYYY"
bibliography: "files/references.bib"
# standard apa7
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl"
# apa7 with inline full references
# csl: files/apa7-inline.csl
final-slide: true
#final-slide-logo: img/psicostat-logo.pdf
toc: true
slide-number: true
qr-code: filippogambarota.github.io
slides-update: "`r Sys.Date()`"
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(echo = TRUE,
                      dev = "pdf",
                      fig.width = 7,
                      fig.asp = 0.618,
                      fig.align = "center",
                      comment = "#>")
```

```{r}
#| label: packages
#| include: false
library(ggplot2)
library(viridis)
```

```{r}
#| label: ggplot2
#| include: false
mtheme <- function(size = 15){
  theme_minimal(base_size = size, 
                base_family = "sans") +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5),
        strip.text = element_text(face = "bold"),
        panel.grid.minor = element_blank())
}

theme_set(mtheme())

# palettes
options(ggplot2.continuous.colour="viridis")
options(ggplot2.continuous.fill = "viridis")
scale_colour_discrete <- scale_colour_viridis_d
scale_fill_discrete <- scale_fill_viridis_d
```

# Section

## Subsection

This is an amazing slide!

- bullet 1
- bullet 2
- bullet n

## Subsection

Another amazing slide

1. bullet 1
2. bullet 2
3. bullet 3

## Subsection

The link [www.google.com](www.google.com)

## Code

```{r}
#| eval: false
library(tidyverse)

iris |> 
  group_by(Species) |> 
  summarise(m = mean(Sepal.Length))
```

## Include references

You can include also some references @Ho2019-kp or [-@Sanchez-Meca2003-tz] or [@Patil2019-ms] @Anikin2025-sw @Miller2024-qi @Sheng2016-ei.

## References {.refs .allowframebreaks}